###

GET http://{{host}}/devices

###

@deviceid_1 = fef217cc-9ff1-45ce-9016-691015fe9607

GET http://{{host}}/devices/{{deviceid_1}}

###


POST http://{{host}}/devices
content-type: application/json

{
  "device": "mkr{{$randomInt 10 100}}-fona",
  "meta": {
    "name": "mkr_gen-fona",
    "description": "MKRZERO Manchox",
    "kind": "MKRZERO1000 + FonaX"
  },
  "auth": {
    "basic": {
      "token": "{{$guid}}"
    }
  },
  "frame": {
    "bigendian": false,
    "bitfields": false
  },
  "sensors": [
    {
      "Meta": {
        "Name": "debug"
      },
      "fmt": {
        "index": 0,
        "fmtchr": "h"
      },
      "sensortypeid": "f0548111-be7f-49db-a01c-ad8037d4a601",
      "conversionid": "5b635746-c7aa-4604-8f8d-0066fe84a5a2"
    },
    {
      "meta": {
        "name": "debug 2"
      },
      "fmt": {
        "index": 1,
        "fmtchr": "H"
      },
      "sensortype": {
        "name": "SIM800P_Battery",
        "meta": {
          "Max": 5020,
          "Min": 1231
        },
        "type": "voltage"
      },
      "conversionid": "5b635746-c7aa-4604-8f8d-0066fe84a5a2"
    },
    {
      "meta": {
        "name": "debug 3"
      },
      "fmt": {
        "index": 2,
        "fmtchr": "I"
      },
      "sensortypeid": "f0548111-be7f-49db-a01c-ad8037d4a601",
      "conversion": {
       "fun": "float_to_int32_alt"
      }
    }
  ]
}

###
POST http://{{host}}/devices
content-type: application/json

{
  "device": "mkr5-fona",
  "meta": {
    "name": "mkr5-fona",
    "description": "MKRZERO Manchox"
  },
  "auth": {
    "basic": {
      "token": "fb2e2658-c6cd-498d-91e6-37ad92bbe89b"
    }
  },
  "frame": {
    "bigendian": false,
    "bitfields": false
  },
  "sensors": [
    {
      "meta": {
        "name": "debug5"
      },
      "fmt": {
        "index": 0,
        "fmtchr": "H"
      },
      "sensortypeid": "f0548111-be7f-49db-a01c-ad8037d4a601",
      "conversionid": "e792ccb9-cef3-44a1-914d-b93b141e2f68"
    }
  ]
}

###

POST http://{{host}}/devices
content-type: application/json

{
  "device": "mkr-minimal-11",
      "meta": {
        "name": "status",
        "kind": "MKR11112"
      },
  "sensors": [
    {
      "meta": {
        "name": "status"
      },
      "fmt": {
        "index": 0,
        "fmtchr": "B"
      },
      "sensortypeid": "8b4f41b0-48ef-4004-b30c-8560b52cd3b7",
      "conversionid": "5b635746-c7aa-4604-8f8d-0066fe84a5a2"
    }
  ]
}

###

@deviceid_del = d1a4cd31-6e2c-458d-8014-6bb844c61757

DELETE http://{{host}}/devices/{{deviceid_del}}

###

GET http://{{host}}/sensortypes

###

POST http://{{host}}/sensortypes
Content-Type: application/json

{
    "Name": "SIM800X_Battery",
    "Meta": {
      "Max": 5000,
      "Min": 0
    },
    "Type": "voltage"
}

###

GET http://{{host}}/sensortypes/8b4f41b0-48ef-4004-b30c-8560b52cd3b7

###

PUT http://{{host}}/sensortypes/c690bd61-b75a-43a1-8d7b-f0d84e068f9b
Content-Type: application/json

{
    "Name": "SIM800X_Battery",
    "Meta": {
      "Max": 5000,
      "Min": 3500
    },
    "Type": "voltage"
}

###

GET http://{{host}}/sensors

###

GET http://{{host}}/sensors/4dc6616e-fadc-4eb1-a3e3-5c4556978df3
###

POST http://{{host}}/sensors
Content-Type: application/json

{
  "meta": { "name": "new_sensor" },
  "fmt": { "index": 2, "fmtchr": "H" },
  "deviceid": "77622684-afc8-4b99-81ff-f76a6239e3f9",
  "sensortypeid": "f0548111-be7f-49db-a01c-ad8037d4a601",
  "conversionid": "e792ccb9-cef3-44a1-914d-b93b141e2f68"
}

###

PUT http://{{host}}/sensors/8b3bfbd6-7646-443c-95a5-da520552a348
Content-Type: application/json

{
  "meta": { "name": "pluvio" },
  "fmt": { "index": 1, "fmtchr": "h" },
  "deviceid": "77622684-afc8-4b99-81ff-f76a6239e3f9",
  "sensortypeid": "cd1f1dd1-8447-4372-a8c5-edb3f173346a",
  "conversionid": "a31dbdaa-1d56-4bc3-8ee6-facb2a9ada55"
}

###

PUT http://{{host}}/sensors/70a3a022-9d66-4af4-b8ce-0994fe4f01f9
Content-Type: application/json

{
  "meta": { "name": "pressure" },
  "conversionid": "0c57d818-f542-45ff-b710-eae777124aed"
}

###

GET http://{{host}}/conversions

###

GET http://{{host}}/conversions/1fe37862-08d4-42a9-a74f-d890e36049ce

###

POST http://{{host}}/conversions
Content-Type: application/json

{
  "Fun": "float_to_int32"
}

###

PUT http://{{host}}/conversions/486b982c-b59b-45e4-bbb6-af4db72b6437
Content-Type: application/json

{
  "Fun": "float_to_uint32"
}
