version: "3"

services:
  klapi:
    image: kiotlog/klapi
    build:
      context: .
      dockerfile: KiotlogAPI/Dockerfile
  webui:
    image: kiotlog/webui
    build:
      context: KiotlogELM
      dockerfile: Dockerfile
